# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Azure PowerShell script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzContext
      
      - name: Get secret from Azure Key Vault
        id: getsecret
        run: |
          echo "SECRET_VALUE=$(az keyvault secret show -n test-secret --vault-name ${{ env.kv_name }} --query value -o tsv)" >> $GITHUB_ENV

      - name: Use the secret
        run: |
          echo "The secret is ${{ env.SECRET_VALUE }}"

            
