# File: .github/workflows/workflow.yml

name: Run Azure Login with Service Principal
on: [push]

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Azure CLI script
        run: |
            az account show

      - name: Azure PowerShell script
        run: |
            Get-AzContext
      
      - name: Get secret from Azure Key Vault
        id: getsecret
        run: |
          echo "SECRET_VALUE=$(az keyvault secret show -n test-secret --vault-name ${{ vars.KV_NAME }} --query value -o tsv)" >> $GITHUB_ENV

      # - name: Use the secret
      #   run: |
      #     echo "The secret is ${{ env.SECRET_VALUE }}"
      #     echo "The key vault name is ${{ vars.KV_NAME }}"

            
