name: Post Article to Dev.to
on:
  workflow_dispatch:
  push:
    paths:
      - 'articles/**.md'  # Adjust this to your preferred path

jobs:
  post_article:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read Article Content
      id: read_article
      run: |
        content="$(echo articles/test.md)"
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "FILE_CONTENT=$content" >> "$GITHUB_ENV
# run: |
# content="$(cat articles/test.md)"
# content="${content//'%'/'%25'}"
# content="${content//$'\n'/'%0A'}"
# content="${content//$'\r'/'%0D'}"
# echo "::set-output name=content::$content"

    # - name: Set output
    #   id: set-output
    #   run: echo "FILE_CONTENT=$(cat articles/test.md)" >> "$GITHUB_ENV"
      
    # - name: Set color
    #   id: color-selector
    #   run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
    # - name: Get color
    #   env:
    #     SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
    #   run: echo "The selected color is $SELECTED_COLOR"


    # - name: Post to Dev.to
    #   env:
    #     FILE_CONTENT: ${{ steps.set-output.outputs.FILE_CONTENT }}

      # run: |
      #   content="$(cat articles/test.md)"
      #   curl -X POST "https://dev.to/api/articles" \
      #   -H "Content-Type: application/json" \
      #   -H "api-key: ${{ secrets.DEVTO_TOKEN }}" \
      #   -d '{
      #     "article": {
      #       "title": "Your Article Title5",
      #       "body_markdown": "${{ env.FILE_CONTENT }}",
      #       "published": false,
      #       "series": "Your Series",
      #       "description": "Short description",
      #       "tags": ["tag1", "tag2"],
      #       "organization_id": 0
      #     }
      #   }'

    - name: Post to Dev.to
      run: |
        curl -X POST "https://dev.to/api/articles" \
        -H "Content-Type: application/json" \
        -H "api-key: ${{ secrets.DEVTO_TOKEN }}" \
        -d '{
          "article": {
            "title": "Your Article Title",
            "body_markdown": "${{ steps.read_article.outputs.FILE_CONTENT }}",
            "published": false,
            "series": "Your Series",
            "main_image": "URL to the main image",
            "canonical_url": "Canonical URL",
            "description": "Short description",
            "tags": ["tag1", "tag2"],
            "organization_id": 0
          }
        }'