name: Post Article to Dev.to
on:
  workflow_dispatch:
  push:
    # paths:
    #   - 'articles/**.md'  # Adjust this to your preferred path
    #   - 

jobs:
  post_article:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - run: python my_script.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests markdown

    - name: Run script
      env:
        DEVTO_TOKEN: ${{ secrets.DEVTO_TOKEN }}
      run: python devto.py testmd.md